app/routes/secretaria.py
from flask import Blueprint, render_template, request, session, flash, redirect, url_for,send_file, jsonify
from app.config import supabase_client
from app.routes.auth import secretaria_required

secretaria_bp = Blueprint('secretaria', __name__, url_prefix='/secretaria')

@secretaria_bp.route('/dashboard')
@secretaria_required
def dashboard():
    if 'role' in session and session['role'] == 'secretaria':
        # Carregar os pedidos dos alunos
        response = supabase_client.table('pedidos_roa').select("*").execute()
        # Carregar os pedidos do aluno
        pedidos_users = response.data
        
        aluno_response = supabase_client.table('usuarios').select("id, nome").execute()
        alunos = aluno_response.data
        
        ficha_response = supabase_client.table('ficha_catalografica').select("*").execute()
        fichasCatalograficas = ficha_response.data
        
        for aluno in alunos:
            for pedido in pedidos_users:
                if aluno['id'] == pedido['id_aluno']:
                    pedido['nome_aluno'] = aluno['nome']
                for ficha in fichasCatalograficas:
                    if pedido['id_aluno'] == ficha['id_aluno']:
                        pedido['ficha'] = ficha['id']
        return render_template('secretaria/dashboard.html',pedidos = pedidos_users,alunos = aluno_response, fichas = fichasCatalograficas)
        
    flash('Acesso não autorizado.', 'danger')
    return redirect(url_for('auth.login'))

@secretaria_bp.route('/detalhes_pedido/<uuid:pedido_id>', methods=['GET', 'POST'])
@secretaria_required
def detalhes_pedido(pedido_id):
    # Carregar informações do pedido
    response = supabase_client.table('pedidos_roa').select("*").eq("id", f"{pedido_id}").execute()
    pedido_aluno = response.data[0]
    
    if pedido_aluno:
        # Obter o id_aluno associado ao pedido
        id_aluno = pedido_aluno['id_aluno']
        
        # Consultar informações do aluno
        aluno_response = supabase_client.table('usuarios').select("matricula, nome").eq("id", id_aluno).execute()
        aluno = aluno_response.data[0] if aluno_response.data else None
    
    if request.method == 'POST':
        
        obs = request.form.get('obs')
        if obs :
            supabase_client.table('pedidos_roa').update({'obs': obs}).eq('id', pedido_id).execute()
            flash("Justificativa enviada com sucesso!")
        acao = request.form.get('acao')
        print(acao)
        if acao == 'aprovar':
            supabase_client.table('pedidos_roa').update({'status': 'Aprovado'}).eq('id', pedido_id).execute()
            flash("Pedido aprovado com sucesso!", "success")
        elif acao == 'reprovar':
            supabase_client.table('pedidos_roa').update({'status': 'Reprovado'}).eq('id', pedido_id).execute()
            flash("Pedido reprovado com sucesso!", "success")
        return redirect(url_for('secretaria.detalhes_pedido', pedido_id=pedido_id))
    
    return render_template('secretaria/detalhes_pedido.html', pedido = pedido_aluno, aluno=aluno)

@secretaria_bp.route('/ficha_catalografica/<uuid:ficha_id>', methods=['GET', 'POST'])
@secretaria_required
def ficha_catalografica(ficha_id):
    response = supabase_client.table('ficha_catalografica').select("*").eq("id", f"{ficha_id}").execute()
    ficha_catalografica_aluno = response.data[0]
    id_aluno = ficha_catalografica_aluno['id_aluno']
    
    aluno_response = supabase_client.table('usuarios').select("matricula, nome").eq("id", id_aluno).execute()
    aluno = aluno_response.data[0] if aluno_response.data else None
    return render_template('secretaria/ficha_catalografica_aluno.html', ficha = ficha_catalografica_aluno, aluno = aluno)

app/templates/secretaria/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard da Secretaria{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/secretaria.css') }}">

<div class="dashboard-container">
    <h2>Pedidos de TCC</h2>

    <!-- Filtro de Status -->
    <div class="filter-container">
        <label for="statusFilter">Filtrar por Status:</label>
        <select id="statusFilter" class="form-select">
            <option value="todos">Todos</option>
            <option value="Pendente">Pendentes</option>
            <option value="Aprovado">Aprovados</option>
            <option value="Reprovado">Reprovado</option>
        </select>
    </div>

    <!-- Lista de Pedidos -->
    <ul id="pedidoList" class="pedido-list">
        {% for pedido in pedidos %}
        <li class="pedido-item" data-status="{{ pedido.status }}">
            <strong>Título:</strong> {{ pedido.titulo_provisorio }} <br>
            <strong>Aluno:</strong> {{ pedido.nome_aluno }}<br>
            <strong>Status:</strong> {{ pedido.status }} <br>
            <a href="{{ url_for('secretaria.detalhes_pedido', pedido_id=pedido.id) }}" class="btn-detalhes">Detalhes</a>
                {% if pedido.ficha and pedido.status == 'Aprovado' %}
                    <a href="{{ url_for('secretaria.ficha_catalografica', ficha_id=pedido.ficha) }}" class="btn-detalhes">Ficha Catalográfica</a>
                {% endif %}
        </li>
        {% endfor %}
    </ul>
</div>
<script >
    document.getElementById('statusFilter').addEventListener('change', function() {
    const selectedStatus = this.value;
    const pedidoItems = document.querySelectorAll('.pedido-item');

    pedidoItems.forEach(item => {
        const pedidoStatus = item.getAttribute('data-status');
        if (selectedStatus === 'todos' || pedidoStatus === selectedStatus) {
            item.style.display = 'block';
        } else {
            item.style.display = 'none';
        }
    });
});</script>
{% endblock%}

app/templates/secretaria/detalhes_pedido.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/secretaria.css') }}">
<div class="container mt-5">
    <div>
        <h3>Informações do Aluno</h3>
        <p><strong>Matrícula:</strong> {{ aluno.matricula }}</p>
        <p><strong>Nome:</strong> {{ aluno.nome }}</p>
    </div>
    <h1>Detalhes do Pedido</h1>
    <hr>
    {% if pedido %}
        <div class="card">
            <div class="card-body">
                <h2 class="card-title" id="titulo">Título: {{ pedido.titulo_provisorio }}</h2>

                <p class="card-text" id="curso"><strong>Curso:</strong> {{ pedido.curso }}</p>
                <p class="card-text" id="semestre"><strong>Semestre:</strong> {{ pedido.semestre }}</p>
                <p class="card-text" id="data-defesa"><strong>Data de defesa:</strong> {{ pedido.data_defesa }}</p>
                <p class="card-text" id="horario"><strong>Horario:</strong> {{ pedido.horario }}</p>
                <p class="card-text" id="turno"><strong>Turno:</strong> {{ pedido.turno }}</p>
                <p class="card-text" id="orientador"><strong>Orientador:</strong> {{ pedido.orientador }}</p>
                <p class="card-text" id="tema_pesquisa"><strong>Tema da pesquisa:</strong> {{ pedido.tema_pesquisa }}</p>
                <p class="card-text" id="atividades_desenvolvidas"><strong>Atividades desenvolvidas:</strong> {{ pedido.atividades_desenvolvidas }}</p>
                <p class="card-text" id="contribuicoes_pesquisa"><strong>Contribuições da pesquisa:</strong> {{ pedido.contribuicoes }}</p>
                
                <h3>Membros da Banca</h3>
                <p class="card-text" id="membro1"><strong>Membro 1:</strong> {{ pedido.membro1 }}</p>
                <p class="card-text" id="membro2"><strong>Membro 2:</strong> {{ pedido.membro2 }}</p>
                <br>
                <p class="card-text" id="status"><strong>Status:</strong> {{ pedido.status }}</p>
        

                <p class="card-text" id="data_envio" value="{{ pedido.created_at[:10] | replace('-', '/') }}">
                <strong>Data de Envio:</strong> {{ pedido.created_at[:10] | replace('-', '/') }}
                </p>

            </div>
        </div>

        <hr>
        {% if pedido.status == 'Pendente' %}
            <button type="button" name="acao" value="aprovar" class="btn btn-success" onclick="confirmarAcao('aprovar','{{ pedido.id }}')">Aprovar</button>
            <button type="button" name="acao" value="reprovar" class="btn btn-danger" onclick="confirmarAcao('reprovar','{{ pedido.id }}')">Reprovar</button>
        <form id="confirmForm" method="POST" style="display: none;" ></form>
        {% elif pedido.status == 'Aprovado'%}
        
            <div >
                <h4 style="color: green; font-weight: bold;">Aluno Aprovado para apresentar</h4>
            </div>
        {% elif pedido.status == 'Reprovado'%}
            <form method="POST" class="justificativa-reprovacao">
            <label for="obs">Justificar reprovação:</label>
            <textarea id="obs" name="obs" rows="4" required ></textarea>
            <button type="submit">Enviar</button>
            </form>
        {% endif %}

    {% else %}
        <p class="text-danger">Pedido não encontrado.</p>
    {% endif %}

    



<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
<script src="{{ url_for('static',filename = 'js/gerador_ficha.js')}}"></script>
<script src="{{ url_for('static', filename = 'js/script.js') }}"></script>
{% endblock %}

app/templates/secretaria/ficha_catalografica_aluno.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/secretaria.css') }}">
<div class="container mt-5">
    <div>
        <h3>Informações do Aluno</h3>
        <p><strong>Matrícula:</strong> {{ aluno.matricula }}</p>
        <p><strong>Nome:</strong> {{ aluno.nome }}</p>
    </div>
    <h1>Detalhes do ficha Catalográfica</h1>
    <hr>
    {% if ficha %}
        <div class="card">
            <div class="card-body">
                <h2 class="card-title" id="titulo">Título: {{ ficha.titulo }}</h2>

                <p class="card-text" id="subtitulo"><strong>Subtítulo:</strong> {{ ficha.sub_titulo or "" }}</p>
                <p class="card-text" id="autor"><strong>Autor:</strong> {{ ficha.nome_autor }}</p>
                <p class="card-text" id="sobrenome_autor"><strong>Sobrenome do Autor:</strong> {{ ficha.sobrenome_autor }}</p>
                <p class="card-text" id="coautor"><strong>Coautor:</strong> {{ ficha.nome_coautor }}</p>
                <p class="card-text" id="sobrenome_coautor"><strong>Sobrenome do Coautor:</strong> {{ ficha.sobrenome_coautor }}</p>
                <p class="card-text" id="curso"><strong>Curso:</strong> {{ ficha.curso }}</p>
                <p class="card-text" id="ano"><strong>Ano de Publicação:</strong> {{ ficha.ano_publicacao }}</p>
                <p class="card-text" id="instituicao"><strong>Instituição:</strong> {{ ficha.instituicao }}</p>
                <p class="card-text" id="cidade"><strong>Cidade:</strong> {{ ficha.cidade }}</p>
                <p class="card-text" id="numero_pag"><strong>Número de Páginas:</strong> {{ ficha.numero_pag }}</p>
                <p class="card-text" id="ilustracao"><strong>Ilustração:</strong> {{ ficha.ilustracao or "" }}</p>
                <p class="card-text" id="tabela"><strong>Tabela:</strong> {{ ficha.tabela or "" }}</p>
                <p class="card-text" id="bibliografia"><strong>Bibliografia:</strong> {{ ficha.bibliografia }}</p>
                <p class="card-text" id="palavras_chaves"><strong>Palavras-Chave:</strong> {{ ficha.palavras_chaves }}</p>
                <p class="card-text" id="cod_cutter"><strong>Código Cutter:</strong> {{ ficha.cod_cutter }}</p>
                <p class="card-text" id="cdd"><strong>CDD:</strong> {{ ficha.cdd }}</p>
                <p class="card-text" id="tamanho"><strong>Tamanho:</strong> {{ ficha.tamanho }}</p>
                <p class="card-text" id="status"><strong>Status:</strong> {{ ficha.status }}</p>
        

                <p class="card-text" id="data_envio" value="{{ ficha.data_envio[:10] | replace('-', '/') }}">
                <strong>Data de Envio:</strong> {{ ficha.data_envio[:10] | replace('-', '/') }}
                </p>

            </div>
        </div>

        <hr>
        
            <div id="result" class="result">

            
            </div>
            <button id="downloadPdf" >Baixar Ficha em PDF</button>
    {% else %}
        <p class="text-danger">ficha não encontrado.</p>
    {% endif %}

    



<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
<script src="{{ url_for('static',filename = 'js/gerador_ficha.js')}}"></script>
<script src="{{ url_for('static', filename = 'js/script.js') }}"></script>
{% endblock %}