app/routes/aluno.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from app.config import supabase_client
from app.utils.gerador_cutter import geradorCutter
from app.routes.auth import aluno_required
import json

with open("app/utils/keywords.json", encoding='utf-8') as keywordsjson:
    keys = json.load(keywordsjson)
    



aluno_bp = Blueprint('aluno', __name__, url_prefix='/aluno')


@aluno_bp.route('/dashboard')
@aluno_required
def dashboard():
    if 'role' in session and session['role'] == 'aluno':
        
        response = supabase_client.table('pedidos_roa').select("*").eq("id_aluno", f"{session['user_id']}").execute()
        
        # Carregar os pedidos do aluno
        pedidoUser = response.data if response.data else None
        
        return render_template('aluno/dashboard.html',pedidos = pedidoUser)
    flash('Acesso não autorizado.', 'danger')
    return redirect(url_for('auth.login'))

@aluno_bp.route('/cadastrar_pedido', methods=['GET', 'POST'])
@aluno_required
def cadastrar_pedido():
    if request.method == 'POST':
        
        semestre = request.form.get("semestre")
        data_defesa = request.form.get("data-defesa")
        horario = request.form.get("horario")
        turno = request.form.get("turno")
        curso = request.form.get("curso")
        orientador = request.form.get("orientador")
        tema_pesquisa = request.form.get("tema_pesquisa")
        titulo_provisorio = request.form.get("titulo_provisorio")
        atividades_desenvolvidas = request.form.get("atividades_desenvolvidas")
        contribuicoes_pesquisa = request.form.get("contribuicoes_pesquisa")
        membro1 = request.form.get("membro1")
        membro2 = request.form.get("membro2")
        
        
        response = (supabase_client.table('pedidos_roa').insert({
            "id_aluno": session['user_id'],
            "semestre": semestre,
            "curso": curso,
            "data_defesa": data_defesa,
            "horario": horario,
            "turno": turno,
            "orientador":orientador,
            "tema_pesquisa":tema_pesquisa,
            "titulo_provisorio": titulo_provisorio,
            "atividades_desenvolvidas": atividades_desenvolvidas,
            "contribuicoes": contribuicoes_pesquisa,
            "membro1": membro1,
            "membro2": membro2
            
        }).execute())
        
        
        flash('Pedido cadastrado com sucesso!', 'success')
        return redirect(url_for('aluno.dashboard'))
    return render_template('aluno/cadastrar_pedido.html')

@aluno_bp.route('/detalhes_pedido/<uuid:pedido_id>', methods=['GET', 'POST'])
@aluno_required
def detalhes_pedido(pedido_id):
    
    response = supabase_client.table('pedidos_roa').select("*").eq("id", f"{pedido_id}").execute()
    pedidoUser = response.data[0]

    if request.method == 'POST':
        if 'delete' in request.form:  # Verifica se a ação é deletar
            if pedidoUser['status'] == 'Pendente':  # Apenas pedidos pendentes podem ser deletados
                supabase_client.table('pedidos_roa').delete().eq('id', pedido_id).execute()
                flash("Pedido deletado com sucesso!", "success")
                return redirect(url_for('aluno.dashboard'))
            else:
                flash("Apenas pedidos com status 'pendente' podem ser deletados.", "danger")
        else:  # Atualizar pedido
            if pedidoUser['status'] == 'Pendente':
                # Obtém dados do formulário
                dados_atualizados = {
                    "semestre": request.form.get("semestre"),
                    "data_defesa": request.form.get("data-defesa"),
                    "horario": request.form.get("horario"),
                    "turno": request.form.get("turno"),
                    "curso": request.form.get("curso"),
                    "orientador": request.form.get("orientador"),
                    "tema_pesquisa": request.form.get("tema_pesquisa"),
                    "titulo_provisorio": request.form.get("titulo_provisorio"),
                    "atividades_desenvolvidas": request.form.get("atividades_desenvolvidas"),
                    "contribuicoes": request.form.get("contribuicoes_pesquisa"),
                    "membro1": request.form.get("membro1"),
                    "membro2": request.form.get("membro2")
                }

                # Atualiza no banco
                supabase_client.table('pedidos_roa').update(dados_atualizados).eq('id', pedido_id).execute()
                flash("Pedido atualizado com sucesso!", "success")
                return redirect(url_for('aluno.dashboard', pedido_id=pedido_id))
    return render_template('aluno/detalhes.html', pedido_id=pedido_id, pedido = pedidoUser)

@aluno_bp.route('/cadastrar_ficha_catalografica', methods=['GET', 'POST'])
@aluno_required
def cadastrar_ficha_catalografica():
    if request.method == 'POST':
        nomeAutor = request.form.get("nomeAutor")
        sobrenomeAutor = request.form.get("sobrenomeAutor")
        nomeCoautor = request.form.get("nomeCoautor")
        sobrenomeCoautor = request.form.get("sobrenomeCoautor")
        titulo = request.form.get("titulo")
        subtitulo = request.form.get("subtitulo")
        curso = request.form.get("curso")
        ano = request.form.get("ano")
        instituicao = request.form.get("instituicao")
        cidade = request.form.get("cidade")
        paginas = request.form.get("paginas")
        ilustracao = request.form.get("ilustracao")
        tabela = request.form.get("tabela")
        tamanho = request.form.get("tamanho")
        bibliografia = request.form.get("bibliografia")
        keywords =  request.form.get("keywords")
        cutter =  geradorCutter(sobrenomeAutor,titulo)
        cdd =  request.form.get("cdd")
        
        response = (supabase_client.table('ficha_catalografica').insert({
            "id_aluno": session['user_id'],
            "nome_autor": nomeAutor,
            "sobrenome_autor": sobrenomeAutor,
            "nome_coautor": nomeCoautor,
            "sobrenome_coautor": sobrenomeCoautor,
            "titulo": titulo,
            "sub_titulo": subtitulo,
            "curso": curso,
            "ano_publicacao": ano,
            "instituicao": instituicao,
            "cidade": cidade,
            "numero_pag": paginas,
            "ilustracao": ilustracao,
            "tabela": tabela,
            "tamanho": tamanho,
            "bibliografia": bibliografia,
            "palavras_chaves": keywords,
            "cod_cutter": cutter,
            "cdd": cdd
            }).execute())
        
        flash('Cadastro de ficha catalografica realizado com sucesso!','success')
        return redirect(url_for('aluno.dashboard'))
        
    return render_template('aluno/cadastrar_ficha_catalografica.html',keywords = keys )

app/templates/aluno/cadastrar_ficha_catalografica.html
{% extends 'base.html' %}

{% block title %}Cadastrar Pedido de TCC{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/aluno.css') }}">
<h2>Cadastrar Pedido de TCC</h2>
<form method="POST" action="{{ url_for('aluno.cadastrar_ficha_catalografica') }}">
    <div class="container">
        <h1>Ficha Catalográfica</h1>

            <h2>Autor(es)</h2>
            <label for="nomeAutor">Nome do Autor:</label>
            <input type="text" id="nomeAutor" name="nomeAutor" required>

            <label for="sobrenomeAutor">Sobrenome do Autor:</label>
            <input type="text" id="sobrenomeAutor" name="sobrenomeAutor" required>

            <label for="nomeCoautor">Nome do Coautor (opcional):</label>
            <input type="text" id="nomeCoautor" name="nomeCoautor">

            <label for="sobrenomeCoautor">Sobrenome do Coautor (opcional):</label>
            <input type="text" id="sobrenomeCoautor" name="sobrenomeCoautor">

            <h2>Trabalho</h2>
            <label for="titulo">Título da Obra:</label>
            <input type="text" id="titulo" name="titulo" required>

            <label for="subtitulo">Subtítulo da Obra (opcional):</label>
            <input type="text" id="subtitulo" name="subtitulo">

            <label for="curso">Curso:</label>
            <select id="curso" name="curso" required>
                <option value="Análise e Desenvolvimento de Sistemas">Análise e Desenvolvimento de Sistemas</option>
                <option value="Sistemas de Informação">Sistemas de Informação</option>
                <option value="Gestão Ambiental">Gestão Ambiental</option>
            </select>

            <label for="ano">Ano de Publicação:</label>
            <input type="number" id="ano" name="ano" required>

            <label for="instituicao">Instituição:</label>
            <input type="text" id="instituicao" name="instituicao" value="Faculdade de Educação Tecnológica do Estado do Rio de Janeiro" readonly>

            <label for="cidade">Cidade:</label>
            <input type="text" id="cidade" name="cidade" value="Paracambi" readonly>

            <label for="paginas">Número de Páginas: </label>
            <h3>As páginas começam a ser contadas a partir da folha de rosto</h3>
            <input type="number" id="paginas" name="paginas" required>
            <input type="hidden" name="paginas1" value="As páginas devem ser contadas a partir da folha de rosto.">

            <label for="ilustracaoCheckbox">Tem ilustração?</label>
            <input type="checkbox" id="ilustracaoCheckbox" onchange="toggleIlustracaoField()">
            <div id="ilustracaoField" style="display: none;">
                <label for="ilustracao">Quantidade de Ilustrações:</label>
                <input type="number" id="ilustracao" name="ilustracao" value = "0">
            </div>
        
            <label for="tabelaCheckbox">Tem tabela?</label>
            <input type="checkbox" id="tabelaCheckbox" onchange="toggleTabelaField()">
            <div id="tabelaField" style="display: none;">
                <label for="tabela">Quantidade de Tabelas:</label>
                <input type="number" id="tabela" name="tabela"  value = "0">
            </div>

            <label for="tamanho">Tamanho (cm):</label>
            <input type="number" id="tamanho" name="tamanho" value="30" readonly>

            <label for="bibliografia"> Bibliografia: </label>
            <h3>1 - Utilize o formato: 00-00</h3>
            <h3>2 - As páginas começam a ser contadas a partir da 1º folha de referências bibliográficas</h3>
            <input type="text" id="bibliografia"  name="bibliografia" required pattern="^\d{1,3}-\d{1,3}$" title="Formato: 11-11">

            <label for="keywords">Palavras-chave (separadas por vírgula):</label>
            <input type="text" id="keywords" name="keywords" list="keys" required>

            <datalist id="keys">
                <option value="">

            </datalist>

            
            <h3> Para preencher o campo abaixo, escolha o item da tabela CDD que mais se identifica com o resumo do seu TCC.</h3>
            
            <select id="cdd" name="cdd" required>
                {% for key, value in keywords.items() %}
                <option value= '{{ key }} '>{{value}} - {{key}}</option>
                {% endfor %}
            </select>
            <button type="submit">Enviar pedido</button>
    </form>
    <script src="{{ url_for('static', filename = 'js/script.js') }}"></script>
    {% endblock %}

app/templates/aluno/cadastrar_pedido.html
{% extends 'base.html' %}

{% block title %}Cadastrar Pedido de TCC{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/aluno.css') }}">
<h2>Cadastrar Pedido de TCC</h2>
<form method="POST" action="{{ url_for('aluno.cadastrar_pedido') }}">
    <div class="container">
        <h1>REGISTRO DE ORIENTAÇÂO ACADÊMICA </h1>


            <label for="titulo_provisorio">Título provisorio:</label>
            <input type="text" id="titulo_provisorio" name="titulo_provisorio" required>


            <label for="curso">Curso:</label>
            <select id="curso" name="curso" required>
                <option value="Análise e Desenvolvimento de Sistemas">Análise e Desenvolvimento de Sistemas</option>
                <option value="Sistemas de Informação">Sistemas de Informação</option>
                <option value="Gestão Ambiental">Gestão Ambiental</option>
            </select>

            <label for="semestre">Semestre:</label>
            <select id="semestre" name="semestre">
                <option value="2025.1">2025.1</option>
                <option value="2024.2">2024.2</option>
                <option value="2024.1">2024.1</option>
                <option value="2023.2">2023.2</option>
                <option value="2023.1">2023.1</option>
            </select>

            <label for="data-defesa">Data de defesa:</label>
            <input type="date" id="data-defesa" name="data-defesa">

            <label for="horario">Horario:</label>
            <input type="time" id="horario" name="horario">

            <label>Turno:</label>
            <div class="turno-radio">
            <input type="radio" value="manhâ" id="turno" name="turno">Manhã
            <input type="radio" value="noite" id="turno" name="turno">Noite
            </div>

            <label for="orientador">Orientador:</label>
            <input type="text" id="orientador" name="orientador" required>

            <label for="tema_pesquisa">Tema da Pesquisa:</label>
            <input type="text" id="tema_pesquisa" name="tema_pesquisa" required>

            <label for="atividades_desenvolvidas">Atividades Desenvolvidas:</label>
            <textarea id="atividades_desenvolvidas" name="atividades_desenvolvidas" rows="4" required></textarea>

            <label for="contribuicoes_pesquisa">Contribuições da Pesquisa:</label>
            <textarea id="contribuicoes_pesquisa" name="contribuicoes_pesquisa" rows="4" required></textarea>

            <h2>Membros da banca</h2>

            <label for="membro1">Membro 1:</label>
            <input type="text" id="membro1" name="membro1" required>

            <label for="membro2">Membro 2:</label>
            <input type="text" id="membro2" name="membro2" required>
            
            <button type="submit">Enviar pedido</button>
        </form>

        
    </div>
    <script src="{{ url_for('static', filename = 'js/script.js') }}"></script>
{% endblock %}

app/templates/aluno/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard do Aluno{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/aluno.css') }}">
<h2>Bem-vindo, {{ session['nome'] }}</h2>
<p>Aqui estão seus pedidos de TCC:</p>

{% if pedidos %}
<ul>
    {% for pedido in pedidos %}
    <li>
        Título: {{ pedido.titulo_provisorio }} | Status: {{ pedido.status }}
        {% if pedido.status == 'Reprovado'%}
        <span style="color: red; font-weight: bold;">Justificativa: {{ pedido.obs }}</span>
        {% elif pedido.status == 'Aprovado' %}
        <span style="color: green; font-weight: bold;">Apto para apresentar TCC</span>
        {% endif %}
        <div class='option-pedido'>

        <a href="{{ url_for('aluno.detalhes_pedido', pedido_id=pedido.id) }}">Detalhes</a>
    </div>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Você ainda não fez nenhum pedido de TCC.</p>
{% endif %}

<a href="{{ url_for('aluno.cadastrar_pedido') }}">Cadastrar novo pedido</a>
<a href="{{ url_for('aluno.cadastrar_ficha_catalografica') }}">Fazer pedido de ficha catalográfica</a>
{% endblock %}

app/templates/aluno/detalhes.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/aluno.css') }}">
<div class="container mt-5">
    <h1>Detalhes do Pedido</h1>
    <hr>
    {% if pedido %}
        <div class="card mb-4">
            <div class="card-body">
                <p class="card-text"><strong>Status:</strong> {{ pedido.status }}</p>
            </div>
        </div>
        {% if pedido.status == "Pendente" %}
            <form method="POST">
                <label for="titulo_provisorio">Título provisorio:</label>
            <input type="text" id="titulo_provisorio" name="titulo_provisorio" value="{{ pedido.titulo_provisorio }}" required>


            <label for="curso">Curso:</label>
            <select id="curso" name="curso" required value="{{ pedido.curso }}">
                <option value="Análise e Desenvolvimento de Sistemas">Análise e Desenvolvimento de Sistemas</option>
                <option value="Sistemas de Informação">Sistemas de Informação</option>
                <option value="Gestão Ambiental">Gestão Ambiental</option>
            </select>

            <label for="semestre">Semestre:</label>
            <select id="semestre" name="semestre" value="{{ pedido.semestre }}">
                <option value="2025.1">2025.1</option>
                <option value="2024.2">2024.2</option>
                <option value="2024.1">2024.1</option>
                <option value="2023.2">2023.2</option>
                <option value="2023.1">2023.1</option>
            </select>

            <label for="data-defesa">Data de defesa:</label>
            <input type="date" id="data-defesa" name="data-defesa" value="{{ pedido.data_defesa }}">

            <label for="horario">Horario:</label>
            <input type="time" id="horario" name="horario" value="{{ pedido.horario }}">

            <label>Turno:</label>
            <div class="turno-radio">
            <input type="radio" value="manhâ" id="turno" name="turno">Manhã
            <input type="radio" value="noite" id="turno" name="turno">Noite
            </div>

            <label for="orientador">Orientador:</label>
            <input type="text" id="orientador" name="orientador" required value="{{ pedido.orientador }}">

            <label for="tema_pesquisa">Tema da Pesquisa:</label>
            <input type="text" id="tema_pesquisa" name="tema_pesquisa" required value="{{ pedido.tema_pesquisa }}">

            <label for="atividades_desenvolvidas">Atividades Desenvolvidas:</label>
            <textarea id="atividades_desenvolvidas" name="atividades_desenvolvidas" rows="4" value="{{ pedido.atividades_desenvolvidas }}"></textarea>

            <label for="contribuicoes_pesquisa">Contribuições da Pesquisa:</label>
            <textarea id="contribuicoes_pesquisa" name="contribuicoes_pesquisa" rows="4" value="{{ pedido.contribuicoes }}"></textarea>

            <h2>Membros da banca</h2>

            <label for="membro1">Membro 1:</label>
            <input type="text" id="membro1" name="membro1" required value="{{ pedido.membro1 }}">

            <label for="membro2">Membro 2:</label>
            <input type="text" id="membro2" name="membro2" required value="{{ pedido.membro2 }}">
                <div class="button-group mt-3">
                    <button type="submit" class="btn btn-success">Salvar Alterações</button>
                    <button type="submit" name="delete" value="1" class="btn btn-warning" onclick="return confirm('Tem certeza que deseja deletar este pedido?');">
                        Deletar Pedido
                    </button>
                </div>
            </form>
        {% else %}
            <p class="text-danger">Este pedido já foi {{ pedido.status }} e não pode ser editado.</p>
        {% endif %}
    {% else %}
        <p class="text-danger">Pedido não encontrado.</p>
    {% endif %}
</div>
{% endblock %}